email: leajb10@gmail.com
twitter_username: LeaBertoluzzi
github_username:  Leandro-Bertoluzzi

baseurl: "/"
url: "https://leandro-bertoluzzi.github.io"

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Custom styles
sass:
  sass_dir: ./css