title: Leandro's homepage
email: leajb10@gmail.com
description: >- # this means to ignore newlines until "twitter_username:"
  Leandro Bertoluzzi's personal page.
twitter_username: LeaBertoluzzi
github_username:  Leandro-Bertoluzzi

baseurl: "/"
url: "https://leandro-bertoluzzi.github.io"

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-redirect-from